export const dataPeterburgCards = [{
    name: 'идентичность: почему нам сложно меняться?',
    type: 'лекция',
    shortDescription: 'лектор: Мария Бархатова',
    description: `Мы думаем и общаемся с помощью нарратива - историй. Вся наша жизнь состоит из их множества, каждая из них совершенно по разному влияет на нас, какие-то из них легко заметить, а какие-то могут годами прятаться. Далеко не в каждой из этих историй мы являемся авторами, но никогда не поздно обратить на это внимание и переписать их, сделав подлинно своими.</br> психологом Марией Бархатовой рассмотрим идентичность с позиции нарративной практики: </br> На встрече поищем ваши желаемые черты и сделаем первые шаги к их укреплению. А домой заберём инструменты для успешного продолжения.`
    , time: '1 мая, 12:30-13:50',
    adress: ['улица Блохина, 22','Ул Пушкина дом 4'],
    more: '+ ещё 3',
    duration: '1час 20 мин',
    cost: '500₽',
    place: 'Coffee wood',
    phone: '+7 (996) 776-21-22',
    social: 'instagram.com/psihologi_v_bare',
    img: 'https://img.audiomania.ru/images/content/article_2_2021.09.24.jpg'
}, {
    name: 'xачапури и вино',
    type: 'еда и напитки',
    shortDescription: 'капучино, эспрессо и американо в пользу Ночлежки',
    description: 'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Molestiae animi voluptate quos consequuntur quia repudiandae voluptates iste debitis inventore, dolores possimus totam ea illo a hic ex nulla sint! Quod!',
    time: 'Пн-Вс, 10:00-22:00',
    adress: ['Малая Конюшенная улиц...'],
    more: '+ ещё 4',
    duration: '1час 20 мин',
    cost: '500₽',
    place: 'Coffee wood',
    phone: '+7 (996) 776-21-22',
    social: 'instagram.com/psihologi_v_bare',
    img: 'https://static.wixstatic.com/media/d0256a_017b879b16b447929fb5e40bbc8d747c~mv2_d_5436_3624_s_4_2.jpg/v1/fill/w_2500,h_1666,al_c/d0256a_017b879b16b447929fb5e40bbc8d747c~mv2_d_5436_3624_s_4_2.jpg'
}, {
    name: 'coffee therapy',
    type: 'еда и напитки',
    shortDescription: 'кофе и угощения в пользу Ночлежки',
    description: 'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Molestiae animi voluptate quos consequuntur quia repudiandae voluptates iste debitis inventore, dolores possimus totam ea illo a hic ex nulla sint! Quod!',
    time: 'Пн-Вс, 10:00-22:00',
    adress: ['улица Льва Толстого, 5'],
    more: '+ ещё 24',
    duration: '1час 20 мин',
    cost: '500₽',
    place: 'Coffee wood',
    phone: '+7 (996) 776-21-22',
    social: 'instagram.com/psihologi_v_bare',
    img: 'https://avatars.dzeninfra.ru/get-zen_doc/2945823/pub_5f3d053c8b7f123568dff35a_5f3d086c7527a446e744c5be/scale_1200'
}, {
    name: 'апрельский хэллоуин у Ники',
    type: 'посиделки',
    shortDescription: 'закрытое событие',
    description: 'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Molestiae animi voluptate quos consequuntur quia repudiandae voluptates iste debitis inventore, dolores possimus totam ea illo a hic ex nulla sint! Quod!',
    time: '',
    adress: [''],
    more: '',
    duration: '1час 20 мин',
    cost: '500₽',
    place: 'Coffee wood',
    phone: '+7 (996) 776-21-22',
    social: 'instagram.com/psihologi_v_bare',
    img: 'https://espress-help.ru/upload/iblock/25c/25c883787ca0a929aa2083d7e3dde35e.jpg'
}, {
    name: 'идентичность: почему нам сложно меняться?',
    type: 'лекция',
    shortDescription: 'лектор: Мария Бархатова',
    description: 'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Molestiae animi voluptate quos consequuntur quia repudiandae voluptates iste debitis inventore, dolores possimus totam ea illo a hic ex nulla sint! Quod!',
    time: '1 мая, 12:30-13:50',
    adress: ['улица Блохина, 22'],
    more: '+ ещё 3',
    duration: '1час 20 мин',
    cost: '500₽',
    place: 'Coffee wood',
    phone: '+7 (996) 776-21-22',
    social: 'instagram.com/psihologi_v_bare',
    img: 'https://img.audiomania.ru/images/content/article_2_2021.09.24.jpg'
}]
